/*
 * This file is generated by jOOQ.
 */
package se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;

import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusStop;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusStopRecord extends UpdatableRecordImpl<BusStopRecord> implements Record7<Integer, Integer, String, String, String, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>BUS_STOP.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>BUS_STOP.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>BUS_STOP.STOP_AREA_ID</code>.
     */
    public void setStopAreaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>BUS_STOP.STOP_AREA_ID</code>.
     */
    public Integer getStopAreaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>BUS_STOP.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>BUS_STOP.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>BUS_STOP.NORTH_COORD</code>.
     */
    public void setNorthCoord(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>BUS_STOP.NORTH_COORD</code>.
     */
    public String getNorthCoord() {
        return (String) get(3);
    }

    /**
     * Setter for <code>BUS_STOP.EAST_COORD</code>.
     */
    public void setEastCoord(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>BUS_STOP.EAST_COORD</code>.
     */
    public String getEastCoord() {
        return (String) get(4);
    }

    /**
     * Setter for <code>BUS_STOP.ZONE</code>.
     */
    public void setZone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>BUS_STOP.ZONE</code>.
     */
    public String getZone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>BUS_STOP.EXISTS_FROM</code>.
     */
    public void setExistsFrom(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>BUS_STOP.EXISTS_FROM</code>.
     */
    public LocalDate getExistsFrom() {
        return (LocalDate) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Integer, Integer, String, String, String, String, LocalDate> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Integer, Integer, String, String, String, String, LocalDate> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BusStop.BUS_STOP.ID;
    }

    @Override
    public Field<Integer> field2() {
        return BusStop.BUS_STOP.STOP_AREA_ID;
    }

    @Override
    public Field<String> field3() {
        return BusStop.BUS_STOP.NAME;
    }

    @Override
    public Field<String> field4() {
        return BusStop.BUS_STOP.NORTH_COORD;
    }

    @Override
    public Field<String> field5() {
        return BusStop.BUS_STOP.EAST_COORD;
    }

    @Override
    public Field<String> field6() {
        return BusStop.BUS_STOP.ZONE;
    }

    @Override
    public Field<LocalDate> field7() {
        return BusStop.BUS_STOP.EXISTS_FROM;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getStopAreaId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getNorthCoord();
    }

    @Override
    public String component5() {
        return getEastCoord();
    }

    @Override
    public String component6() {
        return getZone();
    }

    @Override
    public LocalDate component7() {
        return getExistsFrom();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getStopAreaId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getNorthCoord();
    }

    @Override
    public String value5() {
        return getEastCoord();
    }

    @Override
    public String value6() {
        return getZone();
    }

    @Override
    public LocalDate value7() {
        return getExistsFrom();
    }

    @Override
    public BusStopRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public BusStopRecord value2(Integer value) {
        setStopAreaId(value);
        return this;
    }

    @Override
    public BusStopRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public BusStopRecord value4(String value) {
        setNorthCoord(value);
        return this;
    }

    @Override
    public BusStopRecord value5(String value) {
        setEastCoord(value);
        return this;
    }

    @Override
    public BusStopRecord value6(String value) {
        setZone(value);
        return this;
    }

    @Override
    public BusStopRecord value7(LocalDate value) {
        setExistsFrom(value);
        return this;
    }

    @Override
    public BusStopRecord values(Integer value1, Integer value2, String value3, String value4, String value5, String value6, LocalDate value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BusStopRecord
     */
    public BusStopRecord() {
        super(BusStop.BUS_STOP);
    }

    /**
     * Create a detached, initialised BusStopRecord
     */
    public BusStopRecord(Integer id, Integer stopAreaId, String name, String northCoord, String eastCoord, String zone, LocalDate existsFrom) {
        super(BusStop.BUS_STOP);

        setId(id);
        setStopAreaId(stopAreaId);
        setName(name);
        setNorthCoord(northCoord);
        setEastCoord(eastCoord);
        setZone(zone);
        setExistsFrom(existsFrom);
    }
}
