/*
 * This file is generated by jOOQ.
 */
package se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.records;


import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusStopOnLine;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusStopOnLineRecord extends UpdatableRecordImpl<BusStopOnLineRecord> implements Record5<Integer, Integer, String, Integer, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>BUS_STOP_ON_LINE.BUS_LINE_ID</code>.
     */
    public void setBusLineId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>BUS_STOP_ON_LINE.BUS_LINE_ID</code>.
     */
    public Integer getBusLineId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>BUS_STOP_ON_LINE.BUS_STOP_ID</code>.
     */
    public void setBusStopId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>BUS_STOP_ON_LINE.BUS_STOP_ID</code>.
     */
    public Integer getBusStopId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>BUS_STOP_ON_LINE.DIRECTION</code>.
     */
    public void setDirection(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>BUS_STOP_ON_LINE.DIRECTION</code>.
     */
    public String getDirection() {
        return (String) get(2);
    }

    /**
     * Setter for <code>BUS_STOP_ON_LINE.STOP_ORDER</code>.
     */
    public void setStopOrder(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>BUS_STOP_ON_LINE.STOP_ORDER</code>.
     */
    public Integer getStopOrder() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>BUS_STOP_ON_LINE.EXISTS_FROM</code>.
     */
    public void setExistsFrom(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>BUS_STOP_ON_LINE.EXISTS_FROM</code>.
     */
    public LocalDate getExistsFrom() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Integer, Integer, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, String, Integer, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, String, Integer, LocalDate> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return BusStopOnLine.BUS_STOP_ON_LINE.BUS_LINE_ID;
    }

    @Override
    public Field<Integer> field2() {
        return BusStopOnLine.BUS_STOP_ON_LINE.BUS_STOP_ID;
    }

    @Override
    public Field<String> field3() {
        return BusStopOnLine.BUS_STOP_ON_LINE.DIRECTION;
    }

    @Override
    public Field<Integer> field4() {
        return BusStopOnLine.BUS_STOP_ON_LINE.STOP_ORDER;
    }

    @Override
    public Field<LocalDate> field5() {
        return BusStopOnLine.BUS_STOP_ON_LINE.EXISTS_FROM;
    }

    @Override
    public Integer component1() {
        return getBusLineId();
    }

    @Override
    public Integer component2() {
        return getBusStopId();
    }

    @Override
    public String component3() {
        return getDirection();
    }

    @Override
    public Integer component4() {
        return getStopOrder();
    }

    @Override
    public LocalDate component5() {
        return getExistsFrom();
    }

    @Override
    public Integer value1() {
        return getBusLineId();
    }

    @Override
    public Integer value2() {
        return getBusStopId();
    }

    @Override
    public String value3() {
        return getDirection();
    }

    @Override
    public Integer value4() {
        return getStopOrder();
    }

    @Override
    public LocalDate value5() {
        return getExistsFrom();
    }

    @Override
    public BusStopOnLineRecord value1(Integer value) {
        setBusLineId(value);
        return this;
    }

    @Override
    public BusStopOnLineRecord value2(Integer value) {
        setBusStopId(value);
        return this;
    }

    @Override
    public BusStopOnLineRecord value3(String value) {
        setDirection(value);
        return this;
    }

    @Override
    public BusStopOnLineRecord value4(Integer value) {
        setStopOrder(value);
        return this;
    }

    @Override
    public BusStopOnLineRecord value5(LocalDate value) {
        setExistsFrom(value);
        return this;
    }

    @Override
    public BusStopOnLineRecord values(Integer value1, Integer value2, String value3, Integer value4, LocalDate value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BusStopOnLineRecord
     */
    public BusStopOnLineRecord() {
        super(BusStopOnLine.BUS_STOP_ON_LINE);
    }

    /**
     * Create a detached, initialised BusStopOnLineRecord
     */
    public BusStopOnLineRecord(Integer busLineId, Integer busStopId, String direction, Integer stopOrder, LocalDate existsFrom) {
        super(BusStopOnLine.BUS_STOP_ON_LINE);

        setBusLineId(busLineId);
        setBusStopId(busStopId);
        setDirection(direction);
        setStopOrder(stopOrder);
        setExistsFrom(existsFrom);
    }
}
