/*
 * This file is generated by jOOQ.
 */
package se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusLineEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private String    designation;
    private LocalDate existsFrom;

    public BusLineEntity() {}

    public BusLineEntity(BusLineEntity value) {
        this.id = value.id;
        this.designation = value.designation;
        this.existsFrom = value.existsFrom;
    }

    public BusLineEntity(
        Integer   id,
        String    designation,
        LocalDate existsFrom
    ) {
        this.id = id;
        this.designation = designation;
        this.existsFrom = existsFrom;
    }

    /**
     * Getter for <code>BUS_LINE.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>BUS_LINE.ID</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>BUS_LINE.DESIGNATION</code>.
     */
    public String getDesignation() {
        return this.designation;
    }

    /**
     * Setter for <code>BUS_LINE.DESIGNATION</code>.
     */
    public void setDesignation(String designation) {
        this.designation = designation;
    }

    /**
     * Getter for <code>BUS_LINE.EXISTS_FROM</code>.
     */
    public LocalDate getExistsFrom() {
        return this.existsFrom;
    }

    /**
     * Setter for <code>BUS_LINE.EXISTS_FROM</code>.
     */
    public void setExistsFrom(LocalDate existsFrom) {
        this.existsFrom = existsFrom;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BusLineEntity other = (BusLineEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (designation == null) {
            if (other.designation != null)
                return false;
        }
        else if (!designation.equals(other.designation))
            return false;
        if (existsFrom == null) {
            if (other.existsFrom != null)
                return false;
        }
        else if (!existsFrom.equals(other.existsFrom))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.designation == null) ? 0 : this.designation.hashCode());
        result = prime * result + ((this.existsFrom == null) ? 0 : this.existsFrom.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BusLineEntity (");

        sb.append(id);
        sb.append(", ").append(designation);
        sb.append(", ").append(existsFrom);

        sb.append(")");
        return sb.toString();
    }
}
