/*
 * This file is generated by jOOQ.
 */
package se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusStopEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    private Integer   id;
    private Integer   stopAreaId;
    private String    name;
    private String    northCoord;
    private String    eastCoord;
    private String    zone;
    private LocalDate existsFrom;

    public BusStopEntity() {}

    public BusStopEntity(BusStopEntity value) {
        this.id = value.id;
        this.stopAreaId = value.stopAreaId;
        this.name = value.name;
        this.northCoord = value.northCoord;
        this.eastCoord = value.eastCoord;
        this.zone = value.zone;
        this.existsFrom = value.existsFrom;
    }

    public BusStopEntity(
        Integer   id,
        Integer   stopAreaId,
        String    name,
        String    northCoord,
        String    eastCoord,
        String    zone,
        LocalDate existsFrom
    ) {
        this.id = id;
        this.stopAreaId = stopAreaId;
        this.name = name;
        this.northCoord = northCoord;
        this.eastCoord = eastCoord;
        this.zone = zone;
        this.existsFrom = existsFrom;
    }

    /**
     * Getter for <code>BUS_STOP.ID</code>.
     */
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>BUS_STOP.ID</code>.
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>BUS_STOP.STOP_AREA_ID</code>.
     */
    public Integer getStopAreaId() {
        return this.stopAreaId;
    }

    /**
     * Setter for <code>BUS_STOP.STOP_AREA_ID</code>.
     */
    public void setStopAreaId(Integer stopAreaId) {
        this.stopAreaId = stopAreaId;
    }

    /**
     * Getter for <code>BUS_STOP.NAME</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>BUS_STOP.NAME</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>BUS_STOP.NORTH_COORD</code>.
     */
    public String getNorthCoord() {
        return this.northCoord;
    }

    /**
     * Setter for <code>BUS_STOP.NORTH_COORD</code>.
     */
    public void setNorthCoord(String northCoord) {
        this.northCoord = northCoord;
    }

    /**
     * Getter for <code>BUS_STOP.EAST_COORD</code>.
     */
    public String getEastCoord() {
        return this.eastCoord;
    }

    /**
     * Setter for <code>BUS_STOP.EAST_COORD</code>.
     */
    public void setEastCoord(String eastCoord) {
        this.eastCoord = eastCoord;
    }

    /**
     * Getter for <code>BUS_STOP.ZONE</code>.
     */
    public String getZone() {
        return this.zone;
    }

    /**
     * Setter for <code>BUS_STOP.ZONE</code>.
     */
    public void setZone(String zone) {
        this.zone = zone;
    }

    /**
     * Getter for <code>BUS_STOP.EXISTS_FROM</code>.
     */
    public LocalDate getExistsFrom() {
        return this.existsFrom;
    }

    /**
     * Setter for <code>BUS_STOP.EXISTS_FROM</code>.
     */
    public void setExistsFrom(LocalDate existsFrom) {
        this.existsFrom = existsFrom;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final BusStopEntity other = (BusStopEntity) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        }
        else if (!id.equals(other.id))
            return false;
        if (stopAreaId == null) {
            if (other.stopAreaId != null)
                return false;
        }
        else if (!stopAreaId.equals(other.stopAreaId))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (northCoord == null) {
            if (other.northCoord != null)
                return false;
        }
        else if (!northCoord.equals(other.northCoord))
            return false;
        if (eastCoord == null) {
            if (other.eastCoord != null)
                return false;
        }
        else if (!eastCoord.equals(other.eastCoord))
            return false;
        if (zone == null) {
            if (other.zone != null)
                return false;
        }
        else if (!zone.equals(other.zone))
            return false;
        if (existsFrom == null) {
            if (other.existsFrom != null)
                return false;
        }
        else if (!existsFrom.equals(other.existsFrom))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.stopAreaId == null) ? 0 : this.stopAreaId.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.northCoord == null) ? 0 : this.northCoord.hashCode());
        result = prime * result + ((this.eastCoord == null) ? 0 : this.eastCoord.hashCode());
        result = prime * result + ((this.zone == null) ? 0 : this.zone.hashCode());
        result = prime * result + ((this.existsFrom == null) ? 0 : this.existsFrom.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("BusStopEntity (");

        sb.append(id);
        sb.append(", ").append(stopAreaId);
        sb.append(", ").append(name);
        sb.append(", ").append(northCoord);
        sb.append(", ").append(eastCoord);
        sb.append(", ").append(zone);
        sb.append(", ").append(existsFrom);

        sb.append(")");
        return sb.toString();
    }
}
