/*
 * This file is generated by jOOQ.
 */
package se.npet.trafiklab.buslines.adapters.outbound.db.jooq;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusStop;


/**
 * A class modelling indexes of tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_BUS_STOP_NAME = Internal.createIndex(DSL.name("IDX_BUS_STOP_NAME"), BusStop.BUS_STOP, new OrderField[] { BusStop.BUS_STOP.NAME }, false);
}
