/*
 * This file is generated by jOOQ.
 */
package se.npet.trafiklab.buslines.adapters.outbound.db.jooq;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusLine;
import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusStop;
import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusStopOnLine;
import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.records.BusLineRecord;
import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.records.BusStopOnLineRecord;
import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.records.BusStopRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<BusLineRecord> CONSTRAINT_E = Internal.createUniqueKey(BusLine.BUS_LINE, DSL.name("CONSTRAINT_E"), new TableField[] { BusLine.BUS_LINE.ID }, true);
    public static final UniqueKey<BusStopRecord> CONSTRAINT_EB = Internal.createUniqueKey(BusStop.BUS_STOP, DSL.name("CONSTRAINT_EB"), new TableField[] { BusStop.BUS_STOP.ID }, true);
    public static final UniqueKey<BusStopOnLineRecord> CONSTRAINT_3 = Internal.createUniqueKey(BusStopOnLine.BUS_STOP_ON_LINE, DSL.name("CONSTRAINT_3"), new TableField[] { BusStopOnLine.BUS_STOP_ON_LINE.BUS_LINE_ID, BusStopOnLine.BUS_STOP_ON_LINE.BUS_STOP_ID, BusStopOnLine.BUS_STOP_ON_LINE.DIRECTION }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<BusStopOnLineRecord, BusLineRecord> CONSTRAINT_36 = Internal.createForeignKey(BusStopOnLine.BUS_STOP_ON_LINE, DSL.name("CONSTRAINT_36"), new TableField[] { BusStopOnLine.BUS_STOP_ON_LINE.BUS_LINE_ID }, Keys.CONSTRAINT_E, new TableField[] { BusLine.BUS_LINE.ID }, true);
    public static final ForeignKey<BusStopOnLineRecord, BusStopRecord> CONSTRAINT_36C = Internal.createForeignKey(BusStopOnLine.BUS_STOP_ON_LINE, DSL.name("CONSTRAINT_36C"), new TableField[] { BusStopOnLine.BUS_STOP_ON_LINE.BUS_STOP_ID }, Keys.CONSTRAINT_EB, new TableField[] { BusStop.BUS_STOP.ID }, true);
}
