/*
 * This file is generated by jOOQ.
 */
package se.npet.trafiklab.buslines.adapters.outbound.db.jooq;


import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusLine;
import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusStop;
import se.npet.trafiklab.buslines.adapters.outbound.db.jooq.tables.BusStopOnLine;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>BUS_LINE</code>.
     */
    public static final BusLine BUS_LINE = BusLine.BUS_LINE;

    /**
     * The table <code>BUS_STOP</code>.
     */
    public static final BusStop BUS_STOP = BusStop.BUS_STOP;

    /**
     * The table <code>BUS_STOP_ON_LINE</code>.
     */
    public static final BusStopOnLine BUS_STOP_ON_LINE = BusStopOnLine.BUS_STOP_ON_LINE;
}
